version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: memorialyze_user
      POSTGRES_PASSWORD: memorialyze_password
      POSTGRES_DB: memorialyze_archive
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - memorialyze-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - memorialyze-network

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    volumes:
      - localstack-data:/tmp/localstack
    networks:
      - memorialyze-network

  # For local development, we'll run the app outside of Docker
  # Later, we'll add configurations for the app services

volumes:
  postgres-data:
  localstack-data:

networks:
  memorialyze-network:
    driver: bridge
